# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.security_services.models.dos_protection_rules_protection import DosProtectionRulesProtection

class TestDosProtectionRulesProtection(unittest.TestCase):
    """DosProtectionRulesProtection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DosProtectionRulesProtection:
        """Test DosProtectionRulesProtection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DosProtectionRulesProtection`
        """
        model = DosProtectionRulesProtection()
        if include_optional:
            return DosProtectionRulesProtection(
                aggregate = scm.security_services.models.dos_protection_rules_protection_aggregate.dos_protection_rules_protection_aggregate(
                    profile = '', ),
                classified = scm.security_services.models.dos_protection_rules_protection_classified.dos_protection_rules_protection_classified(
                    classification_criteria = scm.security_services.models.dos_protection_rules_protection_classified_classification_criteria.dos_protection_rules_protection_classified_classification_criteria(
                        address = 'source-ip-only', ), 
                    profile = '', )
            )
        else:
            return DosProtectionRulesProtection(
        )
        """

    def testDosProtectionRulesProtection(self):
        """Test DosProtectionRulesProtection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
