# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_security_services.api.dns_security_profiles_api import DNSSecurityProfilesApi


class TestDNSSecurityProfilesApi(unittest.TestCase):
    """DNSSecurityProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DNSSecurityProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_dns_security_profiles(self) -> None:
        """Test case for create_dns_security_profiles

        Create a DNS security profile
        """
        pass

    def test_delete_dns_security_profiles_by_id(self) -> None:
        """Test case for delete_dns_security_profiles_by_id

        Delete a DNS security profile
        """
        pass

    def test_get_dns_security_profiles_by_id(self) -> None:
        """Test case for get_dns_security_profiles_by_id

        Get a DNS security profile
        """
        pass

    def test_list_dns_security_profiles(self) -> None:
        """Test case for list_dns_security_profiles

        List DNS security profiles
        """
        pass

    def test_update_dns_security_profiles_by_id(self) -> None:
        """Test case for update_dns_security_profiles_by_id

        Update a DNS security profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
