# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_security_services.models.file_blocking_profiles import FileBlockingProfiles

class TestFileBlockingProfiles(unittest.TestCase):
    """FileBlockingProfiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileBlockingProfiles:
        """Test FileBlockingProfiles
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileBlockingProfiles`
        """
        model = FileBlockingProfiles()
        if include_optional:
            return FileBlockingProfiles(
                description = '',
                device = 'My Device',
                folder = 'My Folder',
                id = '123e4567-e89b-12d3-a456-426655440000',
                name = '',
                rules = [
                    scm_security_services.models.file_blocking_profiles_rules_inner.file_blocking_profiles_rules_inner(
                        action = 'alert', 
                        application = [
                            'any'
                            ], 
                        direction = 'both', 
                        file_type = [
                            'any'
                            ], 
                        name = '', )
                    ],
                snippet = 'My Snippet'
            )
        else:
            return FileBlockingProfiles(
                name = '',
        )
        """

    def testFileBlockingProfiles(self):
        """Test FileBlockingProfiles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
