# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.security_services.models.internet_rule_type_allow_url_category_inner_file_control import InternetRuleTypeAllowUrlCategoryInnerFileControl

class TestInternetRuleTypeAllowUrlCategoryInnerFileControl(unittest.TestCase):
    """InternetRuleTypeAllowUrlCategoryInnerFileControl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternetRuleTypeAllowUrlCategoryInnerFileControl:
        """Test InternetRuleTypeAllowUrlCategoryInnerFileControl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternetRuleTypeAllowUrlCategoryInnerFileControl`
        """
        model = InternetRuleTypeAllowUrlCategoryInnerFileControl()
        if include_optional:
            return InternetRuleTypeAllowUrlCategoryInnerFileControl(
                download = 'allow-all-file-types',
                upload = 'allow-all-file-types'
            )
        else:
            return InternetRuleTypeAllowUrlCategoryInnerFileControl(
        )
        """

    def testInternetRuleTypeAllowUrlCategoryInnerFileControl(self):
        """Test InternetRuleTypeAllowUrlCategoryInnerFileControl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
