# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.security_services.api.wild_fire_anti_virus_profiles_api import WildFireAntiVirusProfilesApi


class TestWildFireAntiVirusProfilesApi(unittest.TestCase):
    """WildFireAntiVirusProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WildFireAntiVirusProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_wild_fire_anti_virus_profiles(self) -> None:
        """Test case for create_wild_fire_anti_virus_profiles

        Create a WildFire and anti-virus profile
        """
        pass

    def test_delete_wild_fire_anti_virus_profiles_by_id(self) -> None:
        """Test case for delete_wild_fire_anti_virus_profiles_by_id

        Delete a WildFire and anti-virus profile
        """
        pass

    def test_get_wild_fire_anti_virus_profiles_by_id(self) -> None:
        """Test case for get_wild_fire_anti_virus_profiles_by_id

        Get a WildFire and anti-virus profile
        """
        pass

    def test_list_wild_fire_anti_virus_profiles(self) -> None:
        """Test case for list_wild_fire_anti_virus_profiles

        List Wildfire and anti-virus profiles
        """
        pass

    def test_update_wild_fire_anti_virus_profiles_by_id(self) -> None:
        """Test case for update_wild_fire_anti_virus_profiles_by_id

        Update a wildfire and antivirus profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
