# coding: utf-8

"""
    Identity Services

    These APIs are used for defining and managing identity services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scm.identity_services.models.ldap_server_profiles_server_inner import LdapServerProfilesServerInner
from typing import Optional, Set
from typing_extensions import Self

class LdapServerProfiles(BaseModel):
    """
    LdapServerProfiles
    """ # noqa: E501
    base: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The base DN")
    bind_dn: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="The bind DN")
    bind_password: Optional[Annotated[str, Field(strict=True, max_length=121)]] = Field(default=None, description="The bind password")
    bind_timelimit: Optional[StrictStr] = Field(default=None, description="The bind timeout (seconds)")
    device: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The device in which the resource is defined")
    folder: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The folder in which the resource is defined")
    id: StrictStr = Field(description="The UUID of the LDAP server profile")
    ldap_type: Optional[StrictStr] = Field(default=None, description="The LDAP server time")
    name: StrictStr = Field(description="The name of the LDAP server profile")
    retry_interval: Optional[StrictInt] = Field(default=None, description="The search retry interval (seconds)")
    server: List[LdapServerProfilesServerInner] = Field(description="The LDAP server configuration")
    snippet: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The snippet in which the resource is defined")
    ssl: Optional[StrictBool] = Field(default=None, description="Require SSL/TLS secured connection?")
    timelimit: Optional[StrictInt] = Field(default=None, description="The search timeout (seconds)")
    verify_server_certificate: Optional[StrictBool] = Field(default=None, description="Verify server certificate for SSL sessions?")
    __properties: ClassVar[List[str]] = ["base", "bind_dn", "bind_password", "bind_timelimit", "device", "folder", "id", "ldap_type", "name", "retry_interval", "server", "snippet", "ssl", "timelimit", "verify_server_certificate"]

    @field_validator('device')
    def device_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('folder')
    def folder_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('ldap_type')
    def ldap_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active-directory', 'e-directory', 'sun', 'other']):
            raise ValueError("must be one of enum values ('active-directory', 'e-directory', 'sun', 'other')")
        return value

    @field_validator('snippet')
    def snippet_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LdapServerProfiles from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in server (list)
        _items = []
        if self.server:
            for _item_server in self.server:
                if _item_server:
                    _items.append(_item_server.to_dict())
            _dict['server'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LdapServerProfiles from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base": obj.get("base"),
            "bind_dn": obj.get("bind_dn"),
            "bind_password": obj.get("bind_password"),
            "bind_timelimit": obj.get("bind_timelimit"),
            "device": obj.get("device"),
            "folder": obj.get("folder"),
            "id": obj.get("id"),
            "ldap_type": obj.get("ldap_type"),
            "name": obj.get("name"),
            "retry_interval": obj.get("retry_interval"),
            "server": [LdapServerProfilesServerInner.from_dict(_item) for _item in obj["server"]] if obj.get("server") is not None else None,
            "snippet": obj.get("snippet"),
            "ssl": obj.get("ssl"),
            "timelimit": obj.get("timelimit"),
            "verify_server_certificate": obj.get("verify_server_certificate")
        })
        return _obj


