# coding: utf-8

"""
    Configuration Setup

    These APIs are used to define how Strata Cloud Manager configurations are implemented.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from scm.config_setup.models.devices_available_licensess_inner import DevicesAvailableLicensessInner
from scm.config_setup.models.devices_installed_licenses_inner import DevicesInstalledLicensesInner
from typing import Optional, Set
from typing_extensions import Self

class Devices(BaseModel):
    """
    Devices
    """ # noqa: E501
    anti_virus_version: Optional[StrictStr] = None
    app_release_date: Optional[StrictStr] = None
    app_version: Optional[StrictStr] = None
    av_release_date: Optional[StrictStr] = None
    available_licensess: Optional[List[DevicesAvailableLicensessInner]] = None
    connected_since: Optional[StrictStr] = None
    description: Optional[StrictStr] = Field(default=None, description="The description of the device")
    dev_cert_detail: Optional[StrictStr] = None
    dev_cert_expiry_date: Optional[StrictStr] = None
    display_name: Optional[StrictStr] = Field(default=None, description="The display name of the device")
    family: Optional[StrictStr] = Field(default=None, description="The product family of the device")
    folder: StrictStr = Field(description="The folder containing the device")
    gp_client_verion: Optional[StrictStr] = None
    gp_data_version: Optional[StrictStr] = None
    ha_peer_serial: Optional[StrictStr] = None
    ha_peer_state: Optional[StrictStr] = None
    ha_state: Optional[StrictStr] = None
    hostname: Optional[StrictStr] = Field(default=None, description="The hostname of the device")
    id: StrictStr = Field(description="The UUID of the device")
    installed_licenses: Optional[List[DevicesInstalledLicensesInner]] = None
    iot_release_date: Optional[StrictStr] = None
    iot_version: Optional[StrictStr] = None
    ip_v6_address: Optional[StrictStr] = Field(default=None, description="The IPv6 address of the device", alias="ipV6_address")
    ip_address: Optional[StrictStr] = Field(default=None, description="The IPv4 address of the device")
    is_connected: Optional[StrictBool] = None
    labels: Optional[List[StrictStr]] = Field(default=None, description="Labels assigned to the device")
    license_match: Optional[StrictBool] = None
    log_db_version: Optional[StrictStr] = None
    mac_address: Optional[StrictStr] = Field(default=None, description="The MAC address of the device")
    model: Optional[StrictStr] = Field(default=None, description="The model of the device")
    name: StrictStr = Field(description="The name of the device")
    snippets: Optional[List[StrictStr]] = Field(default=None, description="Snippets associated with the device")
    software_version: Optional[StrictStr] = None
    threat_release_date: Optional[StrictStr] = None
    threat_version: Optional[StrictStr] = None
    uptime: Optional[StrictStr] = None
    url_db_type: Optional[StrictStr] = None
    url_db_ver: Optional[StrictStr] = None
    vm_state: Optional[StrictStr] = None
    wf_release_date: Optional[StrictStr] = None
    wf_ver: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["anti_virus_version", "app_release_date", "app_version", "av_release_date", "available_licensess", "connected_since", "description", "dev_cert_detail", "dev_cert_expiry_date", "display_name", "family", "folder", "gp_client_verion", "gp_data_version", "ha_peer_serial", "ha_peer_state", "ha_state", "hostname", "id", "installed_licenses", "iot_release_date", "iot_version", "ipV6_address", "ip_address", "is_connected", "labels", "license_match", "log_db_version", "mac_address", "model", "name", "snippets", "software_version", "threat_release_date", "threat_version", "uptime", "url_db_type", "url_db_ver", "vm_state", "wf_release_date", "wf_ver"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Devices from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "anti_virus_version",
            "app_release_date",
            "app_version",
            "av_release_date",
            "available_licensess",
            "connected_since",
            "dev_cert_detail",
            "dev_cert_expiry_date",
            "family",
            "gp_client_verion",
            "gp_data_version",
            "ha_peer_serial",
            "ha_peer_state",
            "ha_state",
            "hostname",
            "id",
            "installed_licenses",
            "iot_release_date",
            "iot_version",
            "ip_v6_address",
            "ip_address",
            "is_connected",
            "license_match",
            "log_db_version",
            "mac_address",
            "model",
            "software_version",
            "threat_release_date",
            "threat_version",
            "uptime",
            "url_db_type",
            "url_db_ver",
            "vm_state",
            "wf_release_date",
            "wf_ver",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_licensess (list)
        _items = []
        if self.available_licensess:
            for _item_available_licensess in self.available_licensess:
                if _item_available_licensess:
                    _items.append(_item_available_licensess.to_dict())
            _dict['available_licensess'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in installed_licenses (list)
        _items = []
        if self.installed_licenses:
            for _item_installed_licenses in self.installed_licenses:
                if _item_installed_licenses:
                    _items.append(_item_installed_licenses.to_dict())
            _dict['installed_licenses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Devices from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anti_virus_version": obj.get("anti_virus_version"),
            "app_release_date": obj.get("app_release_date"),
            "app_version": obj.get("app_version"),
            "av_release_date": obj.get("av_release_date"),
            "available_licensess": [DevicesAvailableLicensessInner.from_dict(_item) for _item in obj["available_licensess"]] if obj.get("available_licensess") is not None else None,
            "connected_since": obj.get("connected_since"),
            "description": obj.get("description"),
            "dev_cert_detail": obj.get("dev_cert_detail"),
            "dev_cert_expiry_date": obj.get("dev_cert_expiry_date"),
            "display_name": obj.get("display_name"),
            "family": obj.get("family"),
            "folder": obj.get("folder"),
            "gp_client_verion": obj.get("gp_client_verion"),
            "gp_data_version": obj.get("gp_data_version"),
            "ha_peer_serial": obj.get("ha_peer_serial"),
            "ha_peer_state": obj.get("ha_peer_state"),
            "ha_state": obj.get("ha_state"),
            "hostname": obj.get("hostname"),
            "id": obj.get("id"),
            "installed_licenses": [DevicesInstalledLicensesInner.from_dict(_item) for _item in obj["installed_licenses"]] if obj.get("installed_licenses") is not None else None,
            "iot_release_date": obj.get("iot_release_date"),
            "iot_version": obj.get("iot_version"),
            "ipV6_address": obj.get("ipV6_address"),
            "ip_address": obj.get("ip_address"),
            "is_connected": obj.get("is_connected"),
            "labels": obj.get("labels"),
            "license_match": obj.get("license_match"),
            "log_db_version": obj.get("log_db_version"),
            "mac_address": obj.get("mac_address"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "snippets": obj.get("snippets"),
            "software_version": obj.get("software_version"),
            "threat_release_date": obj.get("threat_release_date"),
            "threat_version": obj.get("threat_version"),
            "uptime": obj.get("uptime"),
            "url_db_type": obj.get("url_db_type"),
            "url_db_ver": obj.get("url_db_ver"),
            "vm_state": obj.get("vm_state"),
            "wf_release_date": obj.get("wf_release_date"),
            "wf_ver": obj.get("wf_ver")
        })
        return _obj


