# coding: utf-8

"""
    Configuration Setup

    These APIs are used to define how Strata Cloud Manager configurations are implemented.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SnippetShareProperty(BaseModel):
    """
    SnippetShareProperty
    """ # noqa: E501
    created: Optional[datetime] = None
    created_by: Optional[StrictStr] = None
    donor_tenant: Optional[StrictStr] = None
    donor_tsg: Optional[StrictStr] = None
    error: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    msg_uuid: Optional[StrictStr] = None
    property_name: Optional[StrictStr] = None
    property_value: Optional[StrictStr] = None
    recipient_tenant: Optional[StrictStr] = None
    recipient_tsg: Optional[StrictStr] = None
    snippet_name: Optional[StrictStr] = None
    snippet_uuid: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    updated: Optional[datetime] = None
    updated_by: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created", "created_by", "donor_tenant", "donor_tsg", "error", "id", "msg_uuid", "property_name", "property_value", "recipient_tenant", "recipient_tsg", "snippet_name", "snippet_uuid", "status", "updated", "updated_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnippetShareProperty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created",
            "created_by",
            "donor_tenant",
            "donor_tsg",
            "error",
            "id",
            "msg_uuid",
            "property_name",
            "property_value",
            "recipient_tenant",
            "recipient_tsg",
            "snippet_name",
            "snippet_uuid",
            "status",
            "updated",
            "updated_by",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnippetShareProperty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "created_by": obj.get("created_by"),
            "donor_tenant": obj.get("donor_tenant"),
            "donor_tsg": obj.get("donor_tsg"),
            "error": obj.get("error"),
            "id": obj.get("id"),
            "msg_uuid": obj.get("msg_uuid"),
            "property_name": obj.get("property_name"),
            "property_value": obj.get("property_value"),
            "recipient_tenant": obj.get("recipient_tenant"),
            "recipient_tsg": obj.get("recipient_tsg"),
            "snippet_name": obj.get("snippet_name"),
            "snippet_uuid": obj.get("snippet_uuid"),
            "status": obj.get("status"),
            "updated": obj.get("updated"),
            "updated_by": obj.get("updated_by")
        })
        return _obj


