# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.device_settings.models.motd_banner_settings import MotdBannerSettings

class TestMotdBannerSettings(unittest.TestCase):
    """MotdBannerSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MotdBannerSettings:
        """Test MotdBannerSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MotdBannerSettings`
        """
        model = MotdBannerSettings()
        if include_optional:
            return MotdBannerSettings(
                device = 'My Device',
                folder = 'My Folder',
                id = '123e4567-e89b-12d3-a456-426655440000',
                motd_and_banner = scm.device_settings.models.motd_banner_settings_motd_and_banner.motd_banner_settings_motd_and_banner(
                    banner_footer = '', 
                    banner_footer_color = 'color1', 
                    banner_footer_text_color = 'color1', 
                    banner_header = '', 
                    banner_header_color = 'color1', 
                    banner_header_footer_match = True, 
                    banner_header_text_color = 'color1', 
                    message = '', 
                    motd_color = 'color1', 
                    motd_do_not_display_again = True, 
                    motd_enable = True, 
                    motd_title = '', 
                    severity = 'warning', ),
                snippet = 'My Snippet'
            )
        else:
            return MotdBannerSettings(
        )
        """

    def testMotdBannerSettings(self):
        """Test MotdBannerSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
