# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.device_settings.models.update_schedule_update_schedule_anti_virus_recurring import UpdateScheduleUpdateScheduleAntiVirusRecurring

class TestUpdateScheduleUpdateScheduleAntiVirusRecurring(unittest.TestCase):
    """UpdateScheduleUpdateScheduleAntiVirusRecurring unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateScheduleUpdateScheduleAntiVirusRecurring:
        """Test UpdateScheduleUpdateScheduleAntiVirusRecurring
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateScheduleUpdateScheduleAntiVirusRecurring`
        """
        model = UpdateScheduleUpdateScheduleAntiVirusRecurring()
        if include_optional:
            return UpdateScheduleUpdateScheduleAntiVirusRecurring(
                daily = scm.device_settings.models.update_schedule_update_schedule_anti_virus_recurring_daily.update_schedule_update_schedule_anti_virus_recurring_daily(
                    action = 'download-only', 
                    at = '23:20', ),
                hourly = scm.device_settings.models.update_schedule_update_schedule_anti_virus_recurring_hourly.update_schedule_update_schedule_anti_virus_recurring_hourly(
                    action = 'download-only', 
                    at = 0, ),
                var_none = scm.device_settings.models.none.none(),
                sync_to_peer = True,
                threshold = 1,
                weekly = scm.device_settings.models.update_schedule_update_schedule_anti_virus_recurring_weekly.update_schedule_update_schedule_anti_virus_recurring_weekly(
                    action = 'download-only', 
                    at = '23:20', 
                    day_of_week = 'sunday', )
            )
        else:
            return UpdateScheduleUpdateScheduleAntiVirusRecurring(
                sync_to_peer = True,
        )
        """

    def testUpdateScheduleUpdateScheduleAntiVirusRecurring(self):
        """Test UpdateScheduleUpdateScheduleAntiVirusRecurring"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
