# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.device_settings.models.ha_configurations_group_election_option import HaConfigurationsGroupElectionOption

class TestHaConfigurationsGroupElectionOption(unittest.TestCase):
    """HaConfigurationsGroupElectionOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HaConfigurationsGroupElectionOption:
        """Test HaConfigurationsGroupElectionOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HaConfigurationsGroupElectionOption`
        """
        model = HaConfigurationsGroupElectionOption()
        if include_optional:
            return HaConfigurationsGroupElectionOption(
                device_priority = 1,
                ha_role = 'primary',
                heartbeat_backup = True,
                preemptive = True
            )
        else:
            return HaConfigurationsGroupElectionOption(
        )
        """

    def testHaConfigurationsGroupElectionOption(self):
        """Test HaConfigurationsGroupElectionOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
