# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.device_settings.models.ha_configurations import HaConfigurations

class TestHaConfigurations(unittest.TestCase):
    """HaConfigurations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HaConfigurations:
        """Test HaConfigurations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HaConfigurations`
        """
        model = HaConfigurations()
        if include_optional:
            return HaConfigurations(
                device = 'My Device',
                enabled = True,
                folder = 'My Folder',
                group = scm.device_settings.models.ha_configurations_group.ha_configurations_group(
                    description = 'N/A', 
                    election_option = scm.device_settings.models.ha_configurations_group_election_option.ha_configurations_group_election_option(
                        device_priority = 1, 
                        ha_role = 'primary', 
                        heartbeat_backup = True, 
                        preemptive = True, ), 
                    group_id = 1, 
                    mode = scm.device_settings.models.ha_configurations_group_mode.ha_configurations_group_mode(
                        active_passive = scm.device_settings.models.ha_configurations_group_mode_active_passive.ha_configurations_group_mode_active_passive(
                            monitor_fail_hold_down_time = 1000, 
                            passive_link_state = 'shutdown', ), ), 
                    monitoring = scm.device_settings.models.ha_configurations_group_monitoring.ha_configurations_group_monitoring(
                        link_monitoring = scm.device_settings.models.ha_configurations_group_monitoring_link_monitoring.ha_configurations_group_monitoring_link_monitoring(
                            enabled = True, 
                            failure_condition = 'any', 
                            link_group = [
                                scm.device_settings.models.ha_configurations_group_monitoring_link_monitoring_link_group_inner.ha_configurations_group_monitoring_link_monitoring_link_group_inner(
                                    enabled = True, 
                                    failure_condition = 'any', 
                                    interface = [
                                        ''
                                        ], 
                                    name = '', )
                                ], ), 
                        path_monitoring = scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring.ha_configurations_group_monitoring_path_monitoring(
                            enabled = True, 
                            failure_condition = 'any', 
                            path_group = scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group.ha_configurations_group_monitoring_path_monitoring_path_group(
                                logical_router = [
                                    scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner(
                                        destination_ip_group = [
                                            scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner_destination_ip_group_inner.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner_destination_ip_group_inner(
                                                destination_ip = [
                                                    ''
                                                    ], 
                                                enabled = True, 
                                                failure_condition = 'any', 
                                                name = '', )
                                            ], 
                                        enabled = True, 
                                        failure_condition = 'any', 
                                        name = '', 
                                        ping_count = 3, 
                                        ping_interval = 200, )
                                    ], ), ), ), 
                    peer_ip = '', 
                    peer_ip_backup = '', 
                    peer_serial = '', 
                    state_synchronization = scm.device_settings.models.ha_configurations_group_state_synchronization.ha_configurations_group_state_synchronization(
                        enabled = True, 
                        ha2_keep_alive = scm.device_settings.models.ha_configurations_group_state_synchronization_ha2_keep_alive.ha_configurations_group_state_synchronization_ha2_keep_alive(
                            action = 'log-only', 
                            enabled = True, 
                            threshold = 5000, ), 
                        transport = 'ethernet', ), ),
                interface = scm.device_settings.models.ha_configurations_interface.ha_configurations_interface(
                    ha1 = scm.device_settings.models.ha_configurations_interface_ha1.ha_configurations_interface_ha1(
                        gateway = '', 
                        ip_address = '', 
                        monitor_hold_time = 1000, 
                        netmask = '', 
                        port = 'management', ), 
                    ha1_backup = scm.device_settings.models.ha_configurations_interface_ha1_backup.ha_configurations_interface_ha1_backup(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), 
                    ha2 = scm.device_settings.models.ha_configurations_interface_ha2.ha_configurations_interface_ha2(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), 
                    ha2_backup = scm.device_settings.models.ha_configurations_interface_ha2_backup.ha_configurations_interface_ha2_backup(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), ),
                snippet = 'My Snippet'
            )
        else:
            return HaConfigurations(
                group = scm.device_settings.models.ha_configurations_group.ha_configurations_group(
                    description = 'N/A', 
                    election_option = scm.device_settings.models.ha_configurations_group_election_option.ha_configurations_group_election_option(
                        device_priority = 1, 
                        ha_role = 'primary', 
                        heartbeat_backup = True, 
                        preemptive = True, ), 
                    group_id = 1, 
                    mode = scm.device_settings.models.ha_configurations_group_mode.ha_configurations_group_mode(
                        active_passive = scm.device_settings.models.ha_configurations_group_mode_active_passive.ha_configurations_group_mode_active_passive(
                            monitor_fail_hold_down_time = 1000, 
                            passive_link_state = 'shutdown', ), ), 
                    monitoring = scm.device_settings.models.ha_configurations_group_monitoring.ha_configurations_group_monitoring(
                        link_monitoring = scm.device_settings.models.ha_configurations_group_monitoring_link_monitoring.ha_configurations_group_monitoring_link_monitoring(
                            enabled = True, 
                            failure_condition = 'any', 
                            link_group = [
                                scm.device_settings.models.ha_configurations_group_monitoring_link_monitoring_link_group_inner.ha_configurations_group_monitoring_link_monitoring_link_group_inner(
                                    enabled = True, 
                                    failure_condition = 'any', 
                                    interface = [
                                        ''
                                        ], 
                                    name = '', )
                                ], ), 
                        path_monitoring = scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring.ha_configurations_group_monitoring_path_monitoring(
                            enabled = True, 
                            failure_condition = 'any', 
                            path_group = scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group.ha_configurations_group_monitoring_path_monitoring_path_group(
                                logical_router = [
                                    scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner(
                                        destination_ip_group = [
                                            scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner_destination_ip_group_inner.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner_destination_ip_group_inner(
                                                destination_ip = [
                                                    ''
                                                    ], 
                                                enabled = True, 
                                                failure_condition = 'any', 
                                                name = '', )
                                            ], 
                                        enabled = True, 
                                        failure_condition = 'any', 
                                        name = '', 
                                        ping_count = 3, 
                                        ping_interval = 200, )
                                    ], ), ), ), 
                    peer_ip = '', 
                    peer_ip_backup = '', 
                    peer_serial = '', 
                    state_synchronization = scm.device_settings.models.ha_configurations_group_state_synchronization.ha_configurations_group_state_synchronization(
                        enabled = True, 
                        ha2_keep_alive = scm.device_settings.models.ha_configurations_group_state_synchronization_ha2_keep_alive.ha_configurations_group_state_synchronization_ha2_keep_alive(
                            action = 'log-only', 
                            enabled = True, 
                            threshold = 5000, ), 
                        transport = 'ethernet', ), ),
                interface = scm.device_settings.models.ha_configurations_interface.ha_configurations_interface(
                    ha1 = scm.device_settings.models.ha_configurations_interface_ha1.ha_configurations_interface_ha1(
                        gateway = '', 
                        ip_address = '', 
                        monitor_hold_time = 1000, 
                        netmask = '', 
                        port = 'management', ), 
                    ha1_backup = scm.device_settings.models.ha_configurations_interface_ha1_backup.ha_configurations_interface_ha1_backup(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), 
                    ha2 = scm.device_settings.models.ha_configurations_interface_ha2.ha_configurations_interface_ha2(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), 
                    ha2_backup = scm.device_settings.models.ha_configurations_interface_ha2_backup.ha_configurations_interface_ha2_backup(
                        gateway = '', 
                        ip_address = '', 
                        netmask = '', 
                        port = '', ), ),
        )
        """

    def testHaConfigurations(self):
        """Test HaConfigurations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
