# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scm.device_settings.models.ha_configurations_group_monitoring_path_monitoring_path_group_logical_router_inner_destination_ip_group_inner import HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInnerDestinationIpGroupInner
from typing import Optional, Set
from typing_extensions import Self

class HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInner(BaseModel):
    """
    HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInner
    """ # noqa: E501
    destination_ip_group: Optional[List[HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInnerDestinationIpGroupInner]] = None
    enabled: Optional[StrictBool] = Field(default=True, description="Enable path group?")
    failure_condition: Optional[StrictStr] = Field(default=None, description="Failure condition")
    name: StrictStr = Field(description="Logical router name")
    ping_count: Optional[Annotated[int, Field(le=10, strict=True, ge=3)]] = Field(default=10, description="Ping count")
    ping_interval: Optional[Annotated[int, Field(le=60000, strict=True, ge=200)]] = Field(default=200, description="Ping interval")
    __properties: ClassVar[List[str]] = ["destination_ip_group", "enabled", "failure_condition", "name", "ping_count", "ping_interval"]

    @field_validator('failure_condition')
    def failure_condition_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all']):
            raise ValueError("must be one of enum values ('any', 'all')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in destination_ip_group (list)
        _items = []
        if self.destination_ip_group:
            for _item_destination_ip_group in self.destination_ip_group:
                if _item_destination_ip_group:
                    _items.append(_item_destination_ip_group.to_dict())
            _dict['destination_ip_group'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destination_ip_group": [HaConfigurationsGroupMonitoringPathMonitoringPathGroupLogicalRouterInnerDestinationIpGroupInner.from_dict(_item) for _item in obj["destination_ip_group"]] if obj.get("destination_ip_group") is not None else None,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "failure_condition": obj.get("failure_condition"),
            "name": obj.get("name"),
            "ping_count": obj.get("ping_count") if obj.get("ping_count") is not None else 10,
            "ping_interval": obj.get("ping_interval") if obj.get("ping_interval") is not None else 200
        })
        return _obj


