# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scm.device_settings.models.ha_configurations_group import HaConfigurationsGroup
from scm.device_settings.models.ha_configurations_interface import HaConfigurationsInterface
from typing import Optional, Set
from typing_extensions import Self

class HaConfigurations(BaseModel):
    """
    HaConfigurations
    """ # noqa: E501
    device: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The device in which the resource is defined")
    enabled: Optional[StrictBool] = True
    folder: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The folder in which the resource is defined")
    group: HaConfigurationsGroup
    interface: HaConfigurationsInterface
    snippet: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The snippet in which the resource is defined")
    __properties: ClassVar[List[str]] = ["device", "enabled", "folder", "group", "interface", "snippet"]

    @field_validator('device')
    def device_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('folder')
    def folder_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('snippet')
    def snippet_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HaConfigurations from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of group
        if self.group:
            _dict['group'] = self.group.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interface
        if self.interface:
            _dict['interface'] = self.interface.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HaConfigurations from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "device": obj.get("device"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "folder": obj.get("folder"),
            "group": HaConfigurationsGroup.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "interface": HaConfigurationsInterface.from_dict(obj["interface"]) if obj.get("interface") is not None else None,
            "snippet": obj.get("snippet")
        })
        return _obj


