# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from scm_device_settings.models.service_settings_services_ntp_servers_primary_ntp_server import ServiceSettingsServicesNtpServersPrimaryNtpServer
from typing import Optional, Set
from typing_extensions import Self

class ServiceSettingsServicesNtpServers(BaseModel):
    """
    ServiceSettingsServicesNtpServers
    """ # noqa: E501
    primary_ntp_server: Optional[ServiceSettingsServicesNtpServersPrimaryNtpServer] = None
    secondary_ntp_server: Optional[ServiceSettingsServicesNtpServersPrimaryNtpServer] = None
    __properties: ClassVar[List[str]] = ["primary_ntp_server", "secondary_ntp_server"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceSettingsServicesNtpServers from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of primary_ntp_server
        if self.primary_ntp_server:
            _dict['primary_ntp_server'] = self.primary_ntp_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secondary_ntp_server
        if self.secondary_ntp_server:
            _dict['secondary_ntp_server'] = self.secondary_ntp_server.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceSettingsServicesNtpServers from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primary_ntp_server": ServiceSettingsServicesNtpServersPrimaryNtpServer.from_dict(obj["primary_ntp_server"]) if obj.get("primary_ntp_server") is not None else None,
            "secondary_ntp_server": ServiceSettingsServicesNtpServersPrimaryNtpServer.from_dict(obj["secondary_ntp_server"]) if obj.get("secondary_ntp_server") is not None else None
        })
        return _obj


