# coding: utf-8

"""
    Device Settings

    These APIs are used for defining and managing device configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from scm.device_settings.models.list_ha_devices200_response import ListHADevices200Response

from scm.device_settings.api_client import ApiClient, RequestSerialized
from scm.device_settings.api_response import ApiResponse
from scm.device_settings.rest import RESTResponseType
from scm.decorators import with_error_handling



class HighAvailabilityDevicesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    @with_error_handling
    def list_ha_devices(
        self,
        folder: Annotated[Optional[StrictStr], Field(description="The folder in which the resource is defined ")] = None,
        snippet: Annotated[Optional[StrictStr], Field(description="The snippet in which the resource is defined ")] = None,
        device: Annotated[Optional[StrictStr], Field(description="The device in which the resource is defined ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListHADevices200Response:
        """List high availability devices

        Retrieve a list of high availability devices. 

        :param folder: The folder in which the resource is defined 
        :type folder: str
        :param snippet: The snippet in which the resource is defined 
        :type snippet: str
        :param device: The device in which the resource is defined 
        :type device: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ha_devices_serialize(
            folder=folder,
            snippet=snippet,
            device=device,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListHADevices200Response",
            '400': "GenericError",
            '401': "GenericError",
            '403': "GenericError",
            '404': "GenericError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    @with_error_handling
    def list_ha_devices_with_http_info(
        self,
        folder: Annotated[Optional[StrictStr], Field(description="The folder in which the resource is defined ")] = None,
        snippet: Annotated[Optional[StrictStr], Field(description="The snippet in which the resource is defined ")] = None,
        device: Annotated[Optional[StrictStr], Field(description="The device in which the resource is defined ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListHADevices200Response]:
        """List high availability devices

        Retrieve a list of high availability devices. 

        :param folder: The folder in which the resource is defined 
        :type folder: str
        :param snippet: The snippet in which the resource is defined 
        :type snippet: str
        :param device: The device in which the resource is defined 
        :type device: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ha_devices_serialize(
            folder=folder,
            snippet=snippet,
            device=device,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListHADevices200Response",
            '400': "GenericError",
            '401': "GenericError",
            '403': "GenericError",
            '404': "GenericError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    @with_error_handling
    def list_ha_devices_without_preload_content(
        self,
        folder: Annotated[Optional[StrictStr], Field(description="The folder in which the resource is defined ")] = None,
        snippet: Annotated[Optional[StrictStr], Field(description="The snippet in which the resource is defined ")] = None,
        device: Annotated[Optional[StrictStr], Field(description="The device in which the resource is defined ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List high availability devices

        Retrieve a list of high availability devices. 

        :param folder: The folder in which the resource is defined 
        :type folder: str
        :param snippet: The snippet in which the resource is defined 
        :type snippet: str
        :param device: The device in which the resource is defined 
        :type device: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_ha_devices_serialize(
            folder=folder,
            snippet=snippet,
            device=device,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListHADevices200Response",
            '400': "GenericError",
            '401': "GenericError",
            '403': "GenericError",
            '404': "GenericError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response



    def fetch_high_availability_devices(
        self,
        name: str,
        folder: Optional[str] = None,
        snippet: Optional[str] = None,
        device: Optional[str] = None,
        **kwargs
    ) -> Optional[Any]:
        """
        Fetch a single high_availability_devices object by name.
    
        This is a convenience method that combines list and filter operations to retrieve
        a specific object by its name within a container (folder, snippet, or device).
    
        Args:
            name: The name of the object to fetch
            folder: The folder in which the resource is defined
            snippet: The snippet in which the resource is defined
            device: The device in which the resource is defined
            **kwargs: Additional keyword arguments
    
        Returns:
            The matching object if found, None otherwise
    
        Example:
            >>> obj = api.fetch_high_availability_devices(name="my-object", folder="Texas")
            >>> if obj:
            ...     print(f"Found: {obj.name}")
        """
        # Use list method with pagination to get all objects
        offset = 0
        limit = kwargs.get('limit', 5000)  # Use larger limit for fetch
    
        while True:
            # Build list parameters dynamically (only include non-None container params)
            list_params = {'offset': offset, 'limit': limit}
            if folder is not None:
                list_params['folder'] = folder
            if snippet is not None:
                list_params['snippet'] = snippet
            if device is not None:
                list_params['device'] = device
            # Note: Not passing 'name' to list() - we do client-side filtering instead
            # Add any additional kwargs (excluding offset/limit/name which we handle separately)
            list_params.update({k: v for k, v in kwargs.items() if k not in ['offset', 'limit', 'name']})
    
            response = self.list_high_availability_devices(**list_params)
    
            # Filter by exact name match
            if hasattr(response, 'data') and response.data:
                for obj in response.data:
                    # If object has 'name' attribute, verify it matches (client-side check)
                    # Otherwise, trust server-side filtering (name was passed to list())
                    if hasattr(obj, 'name'):
                        if obj.name == name:
                            return obj
                    else:
                        # No name attribute, trust server-side filtering, return first result
                        return obj
    
            # Check if we've reached the end
            if not response.data or len(response.data) < limit:
                break
    
            offset += limit
    
        return None

    def _list_ha_devices_serialize(
        self,
        folder,
        snippet,
        device,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if folder is not None:
            
            _query_params.append(('folder', folder))
            
        if snippet is not None:
            
            _query_params.append(('snippet', snippet))
            
        if device is not None:
            
            _query_params.append(('device', device))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'scmToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/ha-devices',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


