# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_objects.models.auto_tag_actions_actions_inner_type_tagging import AutoTagActionsActionsInnerTypeTagging

class TestAutoTagActionsActionsInnerTypeTagging(unittest.TestCase):
    """AutoTagActionsActionsInnerTypeTagging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoTagActionsActionsInnerTypeTagging:
        """Test AutoTagActionsActionsInnerTypeTagging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoTagActionsActionsInnerTypeTagging`
        """
        model = AutoTagActionsActionsInnerTypeTagging()
        if include_optional:
            return AutoTagActionsActionsInnerTypeTagging(
                action = 'add-tag',
                tags = [
                    ''
                    ],
                target = '',
                timeout = 56
            )
        else:
            return AutoTagActionsActionsInnerTypeTagging(
                action = 'add-tag',
                target = '',
        )
        """

    def testAutoTagActionsActionsInnerTypeTagging(self):
        """Test AutoTagActionsActionsInnerTypeTagging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
