# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_objects.models.application_filters import ApplicationFilters

class TestApplicationFilters(unittest.TestCase):
    """ApplicationFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationFilters:
        """Test ApplicationFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationFilters`
        """
        model = ApplicationFilters()
        if include_optional:
            return ApplicationFilters(
                category = [
                    ''
                    ],
                device = 'My Device',
                evasive = True,
                excessive_bandwidth_use = True,
                exclude = [
                    ''
                    ],
                folder = 'My Folder',
                has_known_vulnerabilities = True,
                id = '123e4567-e89b-12d3-a456-426655440000',
                is_saas = True,
                name = '',
                new_appid = True,
                pervasive = True,
                prone_to_misuse = True,
                risk = [
                    1
                    ],
                saas_certifications = [
                    ''
                    ],
                saas_risk = [
                    ''
                    ],
                snippet = 'My Snippet',
                subcategory = [
                    ''
                    ],
                tagging = scm_objects.models.application_filters_tagging.application_filters_tagging(
                    no_tag = True, 
                    tag = [
                        ''
                        ], ),
                technology = [
                    ''
                    ],
                transfers_files = True,
                tunnels_other_apps = True,
                used_by_malware = True
            )
        else:
            return ApplicationFilters(
                name = '',
        )
        """

    def testApplicationFilters(self):
        """Test ApplicationFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
