# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_objects.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_create_services(self) -> None:
        """Test case for create_services

        Create a service
        """
        pass

    def test_delete_services_by_id(self) -> None:
        """Test case for delete_services_by_id

        Delete a service
        """
        pass

    def test_get_services_by_id(self) -> None:
        """Test case for get_services_by_id

        Get a service
        """
        pass

    def test_list_services(self) -> None:
        """Test case for list_services

        List services
        """
        pass

    def test_update_services_by_id(self) -> None:
        """Test case for update_services_by_id

        Update a service
        """
        pass


if __name__ == '__main__':
    unittest.main()
