# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_objects.models.applications_default_ident_by_icmp6_type import ApplicationsDefaultIdentByIcmp6Type

class TestApplicationsDefaultIdentByIcmp6Type(unittest.TestCase):
    """ApplicationsDefaultIdentByIcmp6Type unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationsDefaultIdentByIcmp6Type:
        """Test ApplicationsDefaultIdentByIcmp6Type
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationsDefaultIdentByIcmp6Type`
        """
        model = ApplicationsDefaultIdentByIcmp6Type()
        if include_optional:
            return ApplicationsDefaultIdentByIcmp6Type(
                code = '0,1-255',
                type = '0,1-255'
            )
        else:
            return ApplicationsDefaultIdentByIcmp6Type(
                type = '0,1-255',
        )
        """

    def testApplicationsDefaultIdentByIcmp6Type(self):
        """Test ApplicationsDefaultIdentByIcmp6Type"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
