# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.objects.api.application_groups_api import ApplicationGroupsApi


class TestApplicationGroupsApi(unittest.TestCase):
    """ApplicationGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_application_groups(self) -> None:
        """Test case for create_application_groups

        Create an application group
        """
        pass

    def test_delete_application_groups_by_id(self) -> None:
        """Test case for delete_application_groups_by_id

        Delete an application group
        """
        pass

    def test_get_application_groups_by_id(self) -> None:
        """Test case for get_application_groups_by_id

        Get an application group
        """
        pass

    def test_list_application_groups(self) -> None:
        """Test case for list_application_groups

        List application groups
        """
        pass

    def test_update_application_groups_by_id(self) -> None:
        """Test case for update_application_groups_by_id

        Update an application group
        """
        pass


if __name__ == '__main__':
    unittest.main()
