# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_objects.models.applications_list_response import ApplicationsListResponse

class TestApplicationsListResponse(unittest.TestCase):
    """ApplicationsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationsListResponse:
        """Test ApplicationsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationsListResponse`
        """
        model = ApplicationsListResponse()
        if include_optional:
            return ApplicationsListResponse(
                data = [
                    None
                    ],
                limit = 56,
                offset = 56,
                total = 56
            )
        else:
            return ApplicationsListResponse(
                data = [
                    None
                    ],
                limit = 56,
                offset = 56,
                total = 56,
        )
        """

    def testApplicationsListResponse(self):
        """Test ApplicationsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
