# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.objects.api.applications_api import ApplicationsApi


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_applications(self) -> None:
        """Test case for create_applications

        Create an application
        """
        pass

    def test_delete_applications_by_id(self) -> None:
        """Test case for delete_applications_by_id

        Delete an application
        """
        pass

    def test_get_applications_by_id(self) -> None:
        """Test case for get_applications_by_id

        Get the application by id
        """
        pass

    def test_list_applications(self) -> None:
        """Test case for list_applications

        List applications
        """
        pass

    def test_update_applications_by_id(self) -> None:
        """Test case for update_applications_by_id

        Update an application
        """
        pass


if __name__ == '__main__':
    unittest.main()
