# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.objects.models.hip_objects_disk_backup_criteria import HipObjectsDiskBackupCriteria

class TestHipObjectsDiskBackupCriteria(unittest.TestCase):
    """HipObjectsDiskBackupCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HipObjectsDiskBackupCriteria:
        """Test HipObjectsDiskBackupCriteria
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HipObjectsDiskBackupCriteria`
        """
        model = HipObjectsDiskBackupCriteria()
        if include_optional:
            return HipObjectsDiskBackupCriteria(
                is_installed = True,
                last_backup_time = scm.objects.models.hip_objects_anti_malware_criteria_last_scan_time.hip_objects_anti_malware_criteria_last_scan_time(
                    not_available = scm.objects.models.not_available.not_available(), 
                    not_within = scm.objects.models.hip_objects_anti_malware_criteria_last_scan_time_not_within.hip_objects_anti_malware_criteria_last_scan_time_not_within(
                        days = 1, 
                        hours = 1, ), 
                    within = scm.objects.models.hip_objects_anti_malware_criteria_last_scan_time_not_within.hip_objects_anti_malware_criteria_last_scan_time_not_within(
                        days = 1, 
                        hours = 1, ), )
            )
        else:
            return HipObjectsDiskBackupCriteria(
        )
        """

    def testHipObjectsDiskBackupCriteria(self):
        """Test HipObjectsDiskBackupCriteria"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
