# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from scm.security_services.models.decryption_rules_type_ssl_inbound_inspection import DecryptionRulesTypeSslInboundInspection
from typing import Optional, Set
from typing_extensions import Self

class DecryptionRulesType(BaseModel):
    """
    The type of decryption
    """ # noqa: E501
    ssl_forward_proxy: Optional[Dict[str, Any]] = None
    ssl_inbound_inspection: Optional[DecryptionRulesTypeSslInboundInspection] = None
    __properties: ClassVar[List[str]] = ["ssl_forward_proxy", "ssl_inbound_inspection"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DecryptionRulesType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ssl_inbound_inspection
        if self.ssl_inbound_inspection:
            _dict['ssl_inbound_inspection'] = self.ssl_inbound_inspection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DecryptionRulesType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ssl_forward_proxy": obj.get("ssl_forward_proxy"),
            "ssl_inbound_inspection": DecryptionRulesTypeSslInboundInspection.from_dict(obj["ssl_inbound_inspection"]) if obj.get("ssl_inbound_inspection") is not None else None
        })
        return _obj


