# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scm.security_services.models.dos_protection_rules_action import DosProtectionRulesAction
from scm.security_services.models.dos_protection_rules_protection import DosProtectionRulesProtection
from typing import Optional, Set
from typing_extensions import Self

class DosProtectionRules(BaseModel):
    """
    DosProtectionRules
    """ # noqa: E501
    action: Optional[DosProtectionRulesAction] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Description")
    destination: Optional[List[StrictStr]] = Field(default=None, description="List of destination addresses")
    device: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The device in which the resource is defined")
    disabled: Optional[StrictBool] = Field(default=False, description="Rule disabled?")
    folder: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The folder in which the resource is defined")
    var_from: Optional[List[StrictStr]] = Field(default=None, description="List of source zones", alias="from")
    id: Optional[StrictStr] = Field(default=None, description="The UUID of the DNS security profile")
    log_setting: Optional[StrictStr] = Field(default='Cortex Data Lake', description="Log forwarding profile name")
    name: Annotated[str, Field(strict=True, max_length=31)] = Field(description="Rule name")
    position: Optional[StrictStr] = Field(default='pre', description="Position relative to local device rules")
    protection: Optional[DosProtectionRulesProtection] = None
    schedule: Optional[StrictStr] = Field(default=None, description="Schedule on which to enforce the rule")
    service: Optional[List[StrictStr]] = Field(default=None, description="List of services")
    snippet: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="The snippet in which the resource is defined")
    source: Optional[List[StrictStr]] = Field(default=None, description="List of source addresses")
    source_user: Optional[List[StrictStr]] = Field(default=None, description="List of source users and/or groups.  Reserved words include `any`, `pre-login`, `known-user`, and `unknown`.")
    tag: Optional[List[StrictStr]] = Field(default=None, description="List of tags")
    to: Optional[List[StrictStr]] = Field(default=None, description="List of destination zones")
    __properties: ClassVar[List[str]] = ["action", "description", "destination", "device", "disabled", "folder", "from", "id", "log_setting", "name", "position", "protection", "schedule", "service", "snippet", "source", "source_user", "tag", "to"]

    @field_validator('device')
    def device_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('folder')
    def folder_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    @field_validator('position')
    def position_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pre', 'post']):
            raise ValueError("must be one of enum values ('pre', 'post')")
        return value

    @field_validator('snippet')
    def snippet_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z\d\-_\. ]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z\d\-_\. ]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DosProtectionRules from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of protection
        if self.protection:
            _dict['protection'] = self.protection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DosProtectionRules from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": DosProtectionRulesAction.from_dict(obj["action"]) if obj.get("action") is not None else None,
            "description": obj.get("description"),
            "destination": obj.get("destination"),
            "device": obj.get("device"),
            "disabled": obj.get("disabled") if obj.get("disabled") is not None else False,
            "folder": obj.get("folder"),
            "from": obj.get("from"),
            "id": obj.get("id"),
            "log_setting": obj.get("log_setting") if obj.get("log_setting") is not None else 'Cortex Data Lake',
            "name": obj.get("name"),
            "position": obj.get("position") if obj.get("position") is not None else 'pre',
            "protection": DosProtectionRulesProtection.from_dict(obj["protection"]) if obj.get("protection") is not None else None,
            "schedule": obj.get("schedule"),
            "service": obj.get("service"),
            "snippet": obj.get("snippet"),
            "source": obj.get("source"),
            "source_user": obj.get("source_user"),
            "tag": obj.get("tag"),
            "to": obj.get("to")
        })
        return _obj


