# coding: utf-8

"""
    Security Services

    These APIs are used for defining and managing security services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WildfireAntiVirusProfilesRulesInner(BaseModel):
    """
    WildfireAntiVirusProfilesRulesInner
    """ # noqa: E501
    analysis: Optional[StrictStr] = None
    application: Optional[List[StrictStr]] = None
    direction: Optional[StrictStr] = None
    file_type: Optional[List[StrictStr]] = None
    name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["analysis", "application", "direction", "file_type", "name"]

    @field_validator('analysis')
    def analysis_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['public-cloud', 'private-cloud']):
            raise ValueError("must be one of enum values ('public-cloud', 'private-cloud')")
        return value

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['download', 'upload', 'both']):
            raise ValueError("must be one of enum values ('download', 'upload', 'both')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WildfireAntiVirusProfilesRulesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WildfireAntiVirusProfilesRulesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analysis": obj.get("analysis"),
            "application": obj.get("application"),
            "direction": obj.get("direction"),
            "file_type": obj.get("file_type"),
            "name": obj.get("name")
        })
        return _obj


