# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from scm.network_services.models.bgp_route_maps_route_map_inner_set_aggregator import BgpRouteMapsRouteMapInnerSetAggregator
from scm.network_services.models.bgp_route_maps_route_map_inner_set_ipv4 import BgpRouteMapsRouteMapInnerSetIpv4
from scm.network_services.models.bgp_route_maps_route_map_inner_set_metric import BgpRouteMapsRouteMapInnerSetMetric
from typing import Optional, Set
from typing_extensions import Self

class BgpRouteMapsRouteMapInnerSet(BaseModel):
    """
    BgpRouteMapsRouteMapInnerSet
    """ # noqa: E501
    aggregator: Optional[BgpRouteMapsRouteMapInnerSetAggregator] = None
    aspath_exclude: Optional[List[StrictInt]] = None
    aspath_prepend: Optional[List[StrictInt]] = None
    atomic_aggregate: Optional[StrictBool] = Field(default=None, description="Enable BGP atomic aggregate?")
    ipv4: Optional[BgpRouteMapsRouteMapInnerSetIpv4] = None
    large_community: Optional[List[StrictStr]] = None
    local_preference: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="Local preference")
    metric: Optional[BgpRouteMapsRouteMapInnerSetMetric] = None
    origin: Optional[StrictStr] = Field(default=None, description="Origin")
    originator_id: Optional[StrictStr] = Field(default=None, description="Originator ID")
    overwrite_large_community: Optional[StrictBool] = Field(default=None, description="Overwrite large community?")
    overwrite_regular_community: Optional[StrictBool] = Field(default=None, description="Overwrite regular community?")
    regular_community: Optional[List[StrictStr]] = None
    remove_large_community: Optional[StrictStr] = Field(default=None, description="Remove large community name")
    remove_regular_community: Optional[StrictStr] = Field(default=None, description="Remove regular community name")
    tag: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="Tag")
    weight: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="Weight")
    __properties: ClassVar[List[str]] = ["aggregator", "aspath_exclude", "aspath_prepend", "atomic_aggregate", "ipv4", "large_community", "local_preference", "metric", "origin", "originator_id", "overwrite_large_community", "overwrite_regular_community", "regular_community", "remove_large_community", "remove_regular_community", "tag", "weight"]

    @field_validator('origin')
    def origin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'egp', 'igp', 'incomplete']):
            raise ValueError("must be one of enum values ('none', 'egp', 'igp', 'incomplete')")
        return value

    @field_validator('regular_community')
    def regular_community_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['none', 'blackhole', 'no-peer', 'graceful-shutdown', 'accept-own', 'local-as', 'route-filter-v4', 'route-filter-v6', 'no-advertise', 'no-export', 'internet']):
                raise ValueError("each list item must be one of ('none', 'blackhole', 'no-peer', 'graceful-shutdown', 'accept-own', 'local-as', 'route-filter-v4', 'route-filter-v6', 'no-advertise', 'no-export', 'internet')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BgpRouteMapsRouteMapInnerSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of aggregator
        if self.aggregator:
            _dict['aggregator'] = self.aggregator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ipv4
        if self.ipv4:
            _dict['ipv4'] = self.ipv4.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metric
        if self.metric:
            _dict['metric'] = self.metric.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BgpRouteMapsRouteMapInnerSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aggregator": BgpRouteMapsRouteMapInnerSetAggregator.from_dict(obj["aggregator"]) if obj.get("aggregator") is not None else None,
            "aspath_exclude": obj.get("aspath_exclude"),
            "aspath_prepend": obj.get("aspath_prepend"),
            "atomic_aggregate": obj.get("atomic_aggregate"),
            "ipv4": BgpRouteMapsRouteMapInnerSetIpv4.from_dict(obj["ipv4"]) if obj.get("ipv4") is not None else None,
            "large_community": obj.get("large_community"),
            "local_preference": obj.get("local_preference"),
            "metric": BgpRouteMapsRouteMapInnerSetMetric.from_dict(obj["metric"]) if obj.get("metric") is not None else None,
            "origin": obj.get("origin"),
            "originator_id": obj.get("originator_id"),
            "overwrite_large_community": obj.get("overwrite_large_community"),
            "overwrite_regular_community": obj.get("overwrite_regular_community"),
            "regular_community": obj.get("regular_community"),
            "remove_large_community": obj.get("remove_large_community"),
            "remove_regular_community": obj.get("remove_regular_community"),
            "tag": obj.get("tag"),
            "weight": obj.get("weight")
        })
        return _obj


