# coding: utf-8

"""
    Configuration Setup

    These APIs are used to define how Strata Cloud Manager configurations are implemented.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_config_setup.models.snippet_share_info import SnippetShareInfo

class TestSnippetShareInfo(unittest.TestCase):
    """SnippetShareInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnippetShareInfo:
        """Test SnippetShareInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnippetShareInfo`
        """
        model = SnippetShareInfo()
        if include_optional:
            return SnippetShareInfo(
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                donor_created = 56,
                donor_snippet_file_id = 56,
                donor_snippet_version = 56,
                donor_tenant_id = '',
                donor_tenant_name = '',
                donor_tsg = '',
                error = '',
                id = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                msg_uuid = '',
                properties = [
                    scm_config_setup.models.snippet_share_property.snippet_share_property(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', 
                        donor_tenant = '', 
                        donor_tsg = '', 
                        error = '', 
                        id = 56, 
                        msg_uuid = '', 
                        property_name = '', 
                        property_value = '', 
                        recipient_tenant = '', 
                        recipient_tsg = '', 
                        snippet_name = '', 
                        snippet_uuid = '', 
                        status = '', 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = '', )
                    ],
                recipient_paused_update = True,
                recipient_snippet_file_id = 56,
                recipient_snippet_version = 56,
                recipient_tenant_id = '',
                recipient_tenant_name = '',
                recipient_tsg = '',
                recipient_validate_before_update = True,
                snippet_name = '',
                snippet_uuid = '',
                status = ''
            )
        else:
            return SnippetShareInfo(
        )
        """

    def testSnippetShareInfo(self):
        """Test SnippetShareInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
