# coding: utf-8

"""
    Configuration Setup

    These APIs are used to define how Strata Cloud Manager configurations are implemented.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_config_setup.api.trust_validations_api import TrustValidationsApi


class TestTrustValidationsApi(unittest.TestCase):
    """TrustValidationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrustValidationsApi()

    def tearDown(self) -> None:
        pass

    def test_validate_trust(self) -> None:
        """Test case for validate_trust

        Validates Trust
        """
        pass


if __name__ == '__main__':
    unittest.main()
