# coding: utf-8

"""
    Identity Services

    These APIs are used for defining and managing identity services configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_identity_services.models.authentication_profiles_single_sign_on import AuthenticationProfilesSingleSignOn

class TestAuthenticationProfilesSingleSignOn(unittest.TestCase):
    """AuthenticationProfilesSingleSignOn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticationProfilesSingleSignOn:
        """Test AuthenticationProfilesSingleSignOn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticationProfilesSingleSignOn`
        """
        model = AuthenticationProfilesSingleSignOn()
        if include_optional:
            return AuthenticationProfilesSingleSignOn(
                kerberos_keytab = '',
                realm = ''
            )
        else:
            return AuthenticationProfilesSingleSignOn(
        )
        """

    def testAuthenticationProfilesSingleSignOn(self):
        """Test AuthenticationProfilesSingleSignOn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
