# coding: utf-8

"""
    Objects

    These APIs are used for defining and managing policy object configurations within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from scm_objects.models.payload_format import PayloadFormat
from typing import Optional, Set
from typing_extensions import Self

class HttpServerProfilesFormat(BaseModel):
    """
    HttpServerProfilesFormat
    """ # noqa: E501
    auth: Optional[PayloadFormat] = None
    config: Optional[PayloadFormat] = None
    correlation: Optional[PayloadFormat] = None
    data: Optional[PayloadFormat] = None
    decryption: Optional[PayloadFormat] = None
    globalprotect: Optional[PayloadFormat] = None
    gtp: Optional[PayloadFormat] = None
    hip_match: Optional[PayloadFormat] = None
    iptag: Optional[PayloadFormat] = None
    sctp: Optional[PayloadFormat] = None
    system: Optional[PayloadFormat] = None
    threat: Optional[PayloadFormat] = None
    traffic: Optional[PayloadFormat] = None
    tunnel: Optional[PayloadFormat] = None
    url: Optional[PayloadFormat] = None
    userid: Optional[PayloadFormat] = None
    wildfire: Optional[PayloadFormat] = None
    __properties: ClassVar[List[str]] = ["auth", "config", "correlation", "data", "decryption", "globalprotect", "gtp", "hip_match", "iptag", "sctp", "system", "threat", "traffic", "tunnel", "url", "userid", "wildfire"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpServerProfilesFormat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of auth
        if self.auth:
            _dict['auth'] = self.auth.to_dict()
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of correlation
        if self.correlation:
            _dict['correlation'] = self.correlation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of decryption
        if self.decryption:
            _dict['decryption'] = self.decryption.to_dict()
        # override the default output from pydantic by calling `to_dict()` of globalprotect
        if self.globalprotect:
            _dict['globalprotect'] = self.globalprotect.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gtp
        if self.gtp:
            _dict['gtp'] = self.gtp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hip_match
        if self.hip_match:
            _dict['hip_match'] = self.hip_match.to_dict()
        # override the default output from pydantic by calling `to_dict()` of iptag
        if self.iptag:
            _dict['iptag'] = self.iptag.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sctp
        if self.sctp:
            _dict['sctp'] = self.sctp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of system
        if self.system:
            _dict['system'] = self.system.to_dict()
        # override the default output from pydantic by calling `to_dict()` of threat
        if self.threat:
            _dict['threat'] = self.threat.to_dict()
        # override the default output from pydantic by calling `to_dict()` of traffic
        if self.traffic:
            _dict['traffic'] = self.traffic.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tunnel
        if self.tunnel:
            _dict['tunnel'] = self.tunnel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of url
        if self.url:
            _dict['url'] = self.url.to_dict()
        # override the default output from pydantic by calling `to_dict()` of userid
        if self.userid:
            _dict['userid'] = self.userid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wildfire
        if self.wildfire:
            _dict['wildfire'] = self.wildfire.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpServerProfilesFormat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth": PayloadFormat.from_dict(obj["auth"]) if obj.get("auth") is not None else None,
            "config": PayloadFormat.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "correlation": PayloadFormat.from_dict(obj["correlation"]) if obj.get("correlation") is not None else None,
            "data": PayloadFormat.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "decryption": PayloadFormat.from_dict(obj["decryption"]) if obj.get("decryption") is not None else None,
            "globalprotect": PayloadFormat.from_dict(obj["globalprotect"]) if obj.get("globalprotect") is not None else None,
            "gtp": PayloadFormat.from_dict(obj["gtp"]) if obj.get("gtp") is not None else None,
            "hip_match": PayloadFormat.from_dict(obj["hip_match"]) if obj.get("hip_match") is not None else None,
            "iptag": PayloadFormat.from_dict(obj["iptag"]) if obj.get("iptag") is not None else None,
            "sctp": PayloadFormat.from_dict(obj["sctp"]) if obj.get("sctp") is not None else None,
            "system": PayloadFormat.from_dict(obj["system"]) if obj.get("system") is not None else None,
            "threat": PayloadFormat.from_dict(obj["threat"]) if obj.get("threat") is not None else None,
            "traffic": PayloadFormat.from_dict(obj["traffic"]) if obj.get("traffic") is not None else None,
            "tunnel": PayloadFormat.from_dict(obj["tunnel"]) if obj.get("tunnel") is not None else None,
            "url": PayloadFormat.from_dict(obj["url"]) if obj.get("url") is not None else None,
            "userid": PayloadFormat.from_dict(obj["userid"]) if obj.get("userid") is not None else None,
            "wildfire": PayloadFormat.from_dict(obj["wildfire"]) if obj.get("wildfire") is not None else None
        })
        return _obj


