# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.models.zone_protection_profiles_ipv6 import ZoneProtectionProfilesIpv6

class TestZoneProtectionProfilesIpv6(unittest.TestCase):
    """ZoneProtectionProfilesIpv6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneProtectionProfilesIpv6:
        """Test ZoneProtectionProfilesIpv6
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneProtectionProfilesIpv6`
        """
        model = ZoneProtectionProfilesIpv6()
        if include_optional:
            return ZoneProtectionProfilesIpv6(
                anycast_source = True,
                filter_ext_hdr = scm.network_services.models.zone_protection_profiles_ipv6_filter_ext_hdr.zone_protection_profiles_ipv6_filter_ext_hdr(
                    dest_option_hdr = True, 
                    hop_by_hop_hdr = True, 
                    routing_hdr = True, ),
                icmpv6_too_big_small_mtu_discard = True,
                ignore_inv_pkt = scm.network_services.models.zone_protection_profiles_ipv6_ignore_inv_pkt.zone_protection_profiles_ipv6_ignore_inv_pkt(
                    dest_unreach = True, 
                    param_problem = True, 
                    pkt_too_big = True, 
                    redirect = True, 
                    time_exceeded = True, ),
                ipv4_compatible_address = True,
                needless_fragment_hdr = True,
                options_invalid_ipv6_discard = True,
                reserved_field_set_discard = True,
                routing_header_0 = True,
                routing_header_1 = True,
                routing_header_253 = True,
                routing_header_254 = True,
                routing_header_255 = True,
                routing_header_3 = True,
                routing_header_4_252 = True
            )
        else:
            return ZoneProtectionProfilesIpv6(
        )
        """

    def testZoneProtectionProfilesIpv6(self):
        """Test ZoneProtectionProfilesIpv6"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
