# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.bgp_route_map_redistributions_ospf_rib import BgpRouteMapRedistributionsOspfRib

class TestBgpRouteMapRedistributionsOspfRib(unittest.TestCase):
    """BgpRouteMapRedistributionsOspfRib unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BgpRouteMapRedistributionsOspfRib:
        """Test BgpRouteMapRedistributionsOspfRib
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BgpRouteMapRedistributionsOspfRib`
        """
        model = BgpRouteMapRedistributionsOspfRib()
        if include_optional:
            return BgpRouteMapRedistributionsOspfRib(
                route_map = [
                    scm_network_services.models.bgp_route_map_redistributions_ospf_rib_route_map_inner.bgp_route_map_redistributions_ospf_rib_route_map_inner(
                        action = 'permit', 
                        description = '', 
                        match = scm_network_services.models.bgp_route_map_redistributions_ospf_rib_route_map_inner_match.bgp_route_map_redistributions_ospf_rib_route_map_inner_match(
                            address = scm_network_services.models.bgp_route_map_redistributions_ospf_rib_route_map_inner_match_address.bgp_route_map_redistributions_ospf_rib_route_map_inner_match_address(
                                access_list = '', 
                                prefix_list = '', ), 
                            interface = '', 
                            metric = 0, 
                            next_hop = scm_network_services.models.bgp_route_map_redistributions_ospf_rib_route_map_inner_match_next_hop.bgp_route_map_redistributions_ospf_rib_route_map_inner_match_next_hop(
                                access_list = '', 
                                prefix_list = '', ), 
                            tag = 1, ), 
                        name = 1, 
                        set = scm_network_services.models.bgp_route_map_redistributions_ospf_rib_route_map_inner_set.bgp_route_map_redistributions_ospf_rib_route_map_inner_set(
                            source_address = '', ), )
                    ]
            )
        else:
            return BgpRouteMapRedistributionsOspfRib(
        )
        """

    def testBgpRouteMapRedistributionsOspfRib(self):
        """Test BgpRouteMapRedistributionsOspfRib"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
