# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.vlan_interfaces_ip_inner import VlanInterfacesIpInner

class TestVlanInterfacesIpInner(unittest.TestCase):
    """VlanInterfacesIpInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VlanInterfacesIpInner:
        """Test VlanInterfacesIpInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VlanInterfacesIpInner`
        """
        model = VlanInterfacesIpInner()
        if include_optional:
            return VlanInterfacesIpInner(
                name = ''
            )
        else:
            return VlanInterfacesIpInner(
                name = '',
        )
        """

    def testVlanInterfacesIpInner(self):
        """Test VlanInterfacesIpInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
