# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.logical_routers_vrf_inner_multicast_interface_group_inner_pim_allowed_neighbors_inner import LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner

class TestLogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner(unittest.TestCase):
    """LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner:
        """Test LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner`
        """
        model = LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner()
        if include_optional:
            return LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner(
                name = ''
            )
        else:
            return LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner(
                name = '',
        )
        """

    def testLogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner(self):
        """Test LogicalRoutersVrfInnerMulticastInterfaceGroupInnerPimAllowedNeighborsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
