# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.models.zone_protection_profiles_l2_sec_group_tag_protection import ZoneProtectionProfilesL2SecGroupTagProtection

class TestZoneProtectionProfilesL2SecGroupTagProtection(unittest.TestCase):
    """ZoneProtectionProfilesL2SecGroupTagProtection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneProtectionProfilesL2SecGroupTagProtection:
        """Test ZoneProtectionProfilesL2SecGroupTagProtection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneProtectionProfilesL2SecGroupTagProtection`
        """
        model = ZoneProtectionProfilesL2SecGroupTagProtection()
        if include_optional:
            return ZoneProtectionProfilesL2SecGroupTagProtection(
                tags = [
                    scm.network_services.models.zone_protection_profiles_l2_sec_group_tag_protection_tags_inner.zone_protection_profiles_l2_sec_group_tag_protection_tags_inner(
                        enable = True, 
                        name = '', 
                        tag = '', )
                    ]
            )
        else:
            return ZoneProtectionProfilesL2SecGroupTagProtection(
        )
        """

    def testZoneProtectionProfilesL2SecGroupTagProtection(self):
        """Test ZoneProtectionProfilesL2SecGroupTagProtection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
