# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4 import BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4

class TestBgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4(unittest.TestCase):
    """BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4:
        """Test BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4`
        """
        model = BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4()
        if include_optional:
            return BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4(
                address = scm_network_services.models.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_address.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_address(
                    access_list = '', 
                    prefix_list = '', ),
                next_hop = scm_network_services.models.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_next_hop.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_next_hop(
                    access_list = '', 
                    prefix_list = '', ),
                route_source = scm_network_services.models.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_route_source.bgp_route_map_redistributions_bgp_rib_route_map_inner_match_ipv4_route_source(
                    access_list = '', 
                    prefix_list = '', )
            )
        else:
            return BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4(
        )
        """

    def testBgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4(self):
        """Test BgpRouteMapRedistributionsBgpRibRouteMapInnerMatchIpv4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
