# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa import LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa

class TestLogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa(unittest.TestCase):
    """LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa:
        """Test LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa`
        """
        model = LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa()
        if include_optional:
            return LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa(
                abr = scm_network_services.models.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr(
                    export_list = '', 
                    import_list = '', 
                    inbound_filter_list = '', 
                    nssa_ext_range = [
                        scm_network_services.models.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr_nssa_ext_range_inner.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr_nssa_ext_range_inner(
                            advertise = scm_network_services.models.advertise.advertise(), 
                            name = '', 
                            route_tag = 56, 
                            suppress = scm_network_services.models.suppress.suppress(), )
                        ], 
                    outbound_filter_list = '', ),
                accept_summary = True,
                default_information_originate = scm_network_services.models.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_information_originate.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_information_originate(
                    metric = 56, 
                    metric_type = 'type-1', ),
                default_route = scm_network_services.models.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_route.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_route(
                    advertise = scm_network_services.models.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_route_advertise.logical_routers_vrf_inner_ospf_area_inner_type_nssa_default_route_advertise(
                        metric = 56, 
                        type = 'ext-1', ), 
                    disable = scm_network_services.models.disable.disable(), ),
                no_summary = True,
                nssa_ext_range = [
                    scm_network_services.models.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr_nssa_ext_range_inner.logical_routers_vrf_inner_ospfv3_area_inner_type_nssa_abr_nssa_ext_range_inner(
                        advertise = scm_network_services.models.advertise.advertise(), 
                        name = '', 
                        route_tag = 56, 
                        suppress = scm_network_services.models.suppress.suppress(), )
                    ]
            )
        else:
            return LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa(
        )
        """

    def testLogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa(self):
        """Test LogicalRoutersVrfInnerOspfv3AreaInnerTypeNssa"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
