# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner import LogicalRoutersVrfInnerOspfv3AuthProfileInner

class TestLogicalRoutersVrfInnerOspfv3AuthProfileInner(unittest.TestCase):
    """LogicalRoutersVrfInnerOspfv3AuthProfileInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicalRoutersVrfInnerOspfv3AuthProfileInner:
        """Test LogicalRoutersVrfInnerOspfv3AuthProfileInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicalRoutersVrfInnerOspfv3AuthProfileInner`
        """
        model = LogicalRoutersVrfInnerOspfv3AuthProfileInner()
        if include_optional:
            return LogicalRoutersVrfInnerOspfv3AuthProfileInner(
                ah = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah(
                    md5 = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5(
                        key = '', ), 
                    sha1 = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5(
                        key = '', ), 
                    sha256 = , 
                    sha384 = , 
                    sha512 = , ),
                esp = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp(
                    authentication = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp_authentication.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp_authentication(
                        md5 = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5(
                            key = '', ), 
                        none = scm_network_services.models.none.none(), 
                        sha1 = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5.logical_routers_vrf_inner_ospfv3_auth_profile_inner_ah_md5(
                            key = '', ), 
                        sha256 = , 
                        sha384 = , 
                        sha512 = , ), 
                    encryption = scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp_encryption.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp_encryption(
                        algorithm = '3des', 
                        key = '', ), ),
                name = '',
                spi = ''
            )
        else:
            return LogicalRoutersVrfInnerOspfv3AuthProfileInner(
                name = '',
        )
        """

    def testLogicalRoutersVrfInnerOspfv3AuthProfileInner(self):
        """Test LogicalRoutersVrfInnerOspfv3AuthProfileInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
