# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.models.logical_routers_vrf_inner_ospf_area_inner_interface_inner import LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner

class TestLogicalRoutersVrfInnerOspfAreaInnerInterfaceInner(unittest.TestCase):
    """LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner:
        """Test LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner`
        """
        model = LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner()
        if include_optional:
            return LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner(
                authentication = '',
                bfd = scm.network_services.models.logical_routers_vrf_inner_bgp_global_bfd.logical_routers_vrf_inner_bgp_global_bfd(
                    profile = '', ),
                enable = True,
                link_type = scm.network_services.models.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type(
                    broadcast = scm.network_services.models.broadcast.broadcast(), 
                    p2mp = scm.network_services.models.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type_p2mp.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type_p2mp(
                        neighbor = [
                            scm.network_services.models.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type_p2mp_neighbor_inner.logical_routers_vrf_inner_ospf_area_inner_interface_inner_link_type_p2mp_neighbor_inner(
                                name = '', 
                                priority = 56, )
                            ], ), 
                    p2p = scm.network_services.models.p2p.p2p(), ),
                metric = 56,
                mtu_ignore = True,
                name = '',
                passive = True,
                priority = 56,
                timing = '',
                vr_timing = scm.network_services.models.logical_routers_vrf_inner_ospf_area_inner_interface_inner_vr_timing.logical_routers_vrf_inner_ospf_area_inner_interface_inner_vr_timing(
                    dead_counts = 56, 
                    gr_delay = 56, 
                    hello_interval = 56, 
                    retransmit_interval = 56, 
                    transit_delay = 56, )
            )
        else:
            return LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner(
                name = '',
        )
        """

    def testLogicalRoutersVrfInnerOspfAreaInnerInterfaceInner(self):
        """Test LogicalRoutersVrfInnerOspfAreaInnerInterfaceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
