# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.models.loopback_interfaces_ipv6_address_inner import LoopbackInterfacesIpv6AddressInner

class TestLoopbackInterfacesIpv6AddressInner(unittest.TestCase):
    """LoopbackInterfacesIpv6AddressInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoopbackInterfacesIpv6AddressInner:
        """Test LoopbackInterfacesIpv6AddressInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoopbackInterfacesIpv6AddressInner`
        """
        model = LoopbackInterfacesIpv6AddressInner()
        if include_optional:
            return LoopbackInterfacesIpv6AddressInner(
                enable_on_interface = True,
                interface_id = 'EUI-64',
                name = '2001:DB8::1/128'
            )
        else:
            return LoopbackInterfacesIpv6AddressInner(
        )
        """

    def testLoopbackInterfacesIpv6AddressInner(self):
        """Test LoopbackInterfacesIpv6AddressInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
