# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.models.sdwan_error_correction_profiles_mode_forward_error_correction import SdwanErrorCorrectionProfilesModeForwardErrorCorrection

class TestSdwanErrorCorrectionProfilesModeForwardErrorCorrection(unittest.TestCase):
    """SdwanErrorCorrectionProfilesModeForwardErrorCorrection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SdwanErrorCorrectionProfilesModeForwardErrorCorrection:
        """Test SdwanErrorCorrectionProfilesModeForwardErrorCorrection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SdwanErrorCorrectionProfilesModeForwardErrorCorrection`
        """
        model = SdwanErrorCorrectionProfilesModeForwardErrorCorrection()
        if include_optional:
            return SdwanErrorCorrectionProfilesModeForwardErrorCorrection(
                ratio = '',
                recovery_duration = 56
            )
        else:
            return SdwanErrorCorrectionProfilesModeForwardErrorCorrection(
                ratio = '',
                recovery_duration = 56,
        )
        """

    def testSdwanErrorCorrectionProfilesModeForwardErrorCorrection(self):
        """Test SdwanErrorCorrectionProfilesModeForwardErrorCorrection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
