# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.dhcp_interfaces_server_option import DhcpInterfacesServerOption

class TestDhcpInterfacesServerOption(unittest.TestCase):
    """DhcpInterfacesServerOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DhcpInterfacesServerOption:
        """Test DhcpInterfacesServerOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DhcpInterfacesServerOption`
        """
        model = DhcpInterfacesServerOption()
        if include_optional:
            return DhcpInterfacesServerOption(
                dns = scm_network_services.models.dhcp_interfaces_server_option_dns.dhcp_interfaces_server_option_dns(
                    primary = 'inherited', 
                    secondary = 'inherited', ),
                dns_suffix = 'inherited',
                gateway = '',
                inheritance = scm_network_services.models.dhcp_interfaces_server_option_inheritance.dhcp_interfaces_server_option_inheritance(
                    source = '', ),
                lease = scm_network_services.models.dhcp_interfaces_server_option_lease.dhcp_interfaces_server_option_lease(
                    timeout = 0, 
                    unlimited = scm_network_services.models.unlimited.unlimited(), ),
                nis = scm_network_services.models.dhcp_interfaces_server_option_nis.dhcp_interfaces_server_option_nis(
                    primary = 'inherited', 
                    secondary = 'inherited', ),
                ntp = scm_network_services.models.dhcp_interfaces_server_option_ntp.dhcp_interfaces_server_option_ntp(
                    primary = 'inherited', 
                    secondary = 'inherited', ),
                pop3_server = 'inherited',
                smtp_server = 'inherited',
                subnet_mask = '',
                user_defined = [
                    scm_network_services.models.dhcp_interfaces_server_option_user_defined_inner.dhcp_interfaces_server_option_user_defined_inner(
                        ascii = [
                            ''
                            ], 
                        code = 1, 
                        hex = [
                            ''
                            ], 
                        inherited = True, 
                        ip = [
                            ''
                            ], 
                        name = '', )
                    ],
                wins = scm_network_services.models.dhcp_interfaces_server_option_wins.dhcp_interfaces_server_option_wins(
                    primary = 'inherited', 
                    secondary = 'inherited', )
            )
        else:
            return DhcpInterfacesServerOption(
        )
        """

    def testDhcpInterfacesServerOption(self):
        """Test DhcpInterfacesServerOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
