# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm.network_services.api.qo_s_profiles_api import QoSProfilesApi


class TestQoSProfilesApi(unittest.TestCase):
    """QoSProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QoSProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_qo_s_profiles(self) -> None:
        """Test case for create_qo_s_profiles

        Create a QoS profile
        """
        pass

    def test_delete_qo_s_profiles_by_id(self) -> None:
        """Test case for delete_qo_s_profiles_by_id

        Delete a QoS profile
        """
        pass

    def test_get_qo_s_profiles_by_id(self) -> None:
        """Test case for get_qo_s_profiles_by_id

        Get a QoS profile
        """
        pass

    def test_list_qo_s_profiles(self) -> None:
        """Test case for list_qo_s_profiles

        List QoS profiles
        """
        pass

    def test_update_qo_s_profiles_by_id(self) -> None:
        """Test case for update_qo_s_profiles_by_id

        Update a QoS profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
