# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.api.dhcp_interfaces_api import DHCPInterfacesApi


class TestDHCPInterfacesApi(unittest.TestCase):
    """DHCPInterfacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DHCPInterfacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_dhcp_interfaces(self) -> None:
        """Test case for create_dhcp_interfaces

        Create a DHCP interface
        """
        pass

    def test_delete_dhcp_interfaces_by_id(self) -> None:
        """Test case for delete_dhcp_interfaces_by_id

        Delete a DHCP interface
        """
        pass

    def test_get_dhcp_interfaces_by_id(self) -> None:
        """Test case for get_dhcp_interfaces_by_id

        Get a DHCP interface
        """
        pass

    def test_list_dhcp_interfaces(self) -> None:
        """Test case for list_dhcp_interfaces

        List DHCP interfaces
        """
        pass

    def test_update_dhcp_interfaces_by_id(self) -> None:
        """Test case for update_dhcp_interfaces_by_id

        Update a DHCP interface
        """
        pass


if __name__ == '__main__':
    unittest.main()
