# coding: utf-8

"""
    Network Services

    These APIs are used for defining and managing network services configuration within Strata Cloud Manager.

    The version of the OpenAPI document: 2.0.0
    Contact: support@paloaltonetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scm_network_services.models.logical_routers_vrf_inner_ospfv3_auth_profile_inner_esp_encryption import LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption

class TestLogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption(unittest.TestCase):
    """LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption:
        """Test LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption`
        """
        model = LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption()
        if include_optional:
            return LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption(
                algorithm = '3des',
                key = ''
            )
        else:
            return LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption(
        )
        """

    def testLogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption(self):
        """Test LogicalRoutersVrfInnerOspfv3AuthProfileInnerEspEncryption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
